### ISSUE TITLE
Bug: Anju Inn Reservation Flags are Inconsistent in NPC Soul and Clock Shuffle Settings

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#710]
Something is going on with Anju's Inn Reservation check in MM with Soul Shuffle and Clock Shuffle. Basically, if you obtain either Day 1 clock **OR** Anju's Soul, sometimes, it will randomly act like the Goron reserved the room even if you show up at the time **before** the Postman talks to Anju.

You can see this happen to me here in my most recent Soul Shuffle seed: https://clips.twitch.tv/RepleteCallousEelPRChase-e79g-WbhgUk65oma

When I Song of Timed, repeating the same process, I was able to get the check as normal successfully. I'm not sure how easily reproducible this is but it has happened to Ghunzor and it has happened to me in the above clip. I feel it is worth reporting this and hoping you can look into it and fix it.

**Comment by Revvenn** [comment]
Apparently, this can also happen in ER?

**Comment by Nax** [comment]
Fixed

**Comment by CelestialKitsune** [comment]
This bug has returned, leaving both Revven and I more perplex than before.

**Comment by Revvenn** [comment]
This bug still exists. I had it happen to me recently here: https://clips.twitch.tv/HonorableAffluentClipsdadRuleFive-HUGoXPdpzPNbtxOs

It's still the same problem at the very least: if you do not get the room key check in cycle 1, then the next time you attempt to get it it will fail even if it's the right timeframe the check is available. The reason it happens in ER and souls seeds is because you can't get the check in cycle 1 (more so for souls, but in ER you can easily get lucky and get it cycle 1 and it's fine). I'm not sure what the actual, core issue is but that theory remains true (as we discussed last time this bug was being looked at).

**Comment by Nax** [comment]
This time it should be good
